USE Gerson;
INSERT INTO Editora ( Nome ) VALUES ('Cortez Editora');
INSERT INTO Editora ( Nome ) VALUES ('Coletivo Editorial');
INSERT INTO Editora ( Nome ) VALUES ('Editora Vozes');
INSERT INTO Editora ( Nome ) VALUES ('Editora Record');
INSERT INTO Editora ( Nome ) VALUES ('Panda Books');
INSERT INTO Editora ( Nome ) VALUES ('Qualis');
INSERT INTO Editora ( Nome ) VALUES ('Illuminare');
INSERT INTO Editora ( Nome ) VALUES ('Vivaluz Editora');
INSERT INTO Autor ( Nome ) VALUES ('Machado de Assis' );
INSERT INTO Autor ( Nome ) VALUES ('Clarice Lispector' );
INSERT INTO Autor ( Nome ) VALUES ('Carlos Drummond de Andrade' );
INSERT INTO Autor ( Nome ) VALUES ('Guimarães Rosa' );
INSERT INTO Autor ( Nome ) VALUES ('Jorge Amado' );
INSERT INTO Autor ( Nome ) VALUES ('José de Alencar' );
INSERT INTO Autor ( Nome ) VALUES ('Mário de Andrade' );
INSERT INTO Genero ( Descricao ) VALUES ('Autobiografia' );
INSERT INTO Genero ( Descricao ) VALUES ('Fantasia ' );
INSERT INTO Genero ( Descricao ) VALUES ('Horror' );
INSERT INTO Genero ( Descricao ) VALUES ('Comédia' );
INSERT INTO Genero ( Descricao ) VALUES ('Romance' );
INSERT INTO Genero ( Descricao ) VALUES ('Suspense' );
INSERT INTO Genero ( Descricao ) VALUES ('Guerra' );
INSERT INTO Genero ( Descricao ) VALUES ('Auto-ajuda' );
